/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmarketui;

import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Jah
 */
public class Setup extends javax.swing.JFrame {

    File compFile = null;
    File clientFile = null;
     int traderCount = 0;
    /**
     * Creates new form Setup
     */
    int choice;
   

    public Setup() {
        Object[] temp;
        while (compFile == null || clientFile == null) {

            temp = initialSetup();
            choice = (int) temp[0];
            traderCount = (int) temp[1];
            

            if (choice == 1) {
                System.exit(0);
            }
        }
        System.out.println("hreasd");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsFrame = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        mainPane = new javax.swing.JPanel();
        tradingExchangePanel = new javax.swing.JPanel();
        clientPanel = new javax.swing.JPanel();
        stockPanel = new javax.swing.JPanel();
        clientButton = new javax.swing.JButton();
        tradingExButton = new javax.swing.JButton();
        stockButton = new javax.swing.JButton();

        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        settingsFrame.setTitle("Settings");
        settingsFrame.setMinimumSize(new java.awt.Dimension(400, 600));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout settingsFrameLayout = new javax.swing.GroupLayout(settingsFrame.getContentPane());
        settingsFrame.getContentPane().setLayout(settingsFrameLayout);
        settingsFrameLayout.setHorizontalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        settingsFrameLayout.setVerticalGroup(
            settingsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPane.setLayout(new java.awt.CardLayout());

        tradingExchangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Trading Exchange"));

        javax.swing.GroupLayout tradingExchangePanelLayout = new javax.swing.GroupLayout(tradingExchangePanel);
        tradingExchangePanel.setLayout(tradingExchangePanelLayout);
        tradingExchangePanelLayout.setHorizontalGroup(
            tradingExchangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        tradingExchangePanelLayout.setVerticalGroup(
            tradingExchangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        mainPane.add(tradingExchangePanel, "card2");

        clientPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Client"));

        javax.swing.GroupLayout clientPanelLayout = new javax.swing.GroupLayout(clientPanel);
        clientPanel.setLayout(clientPanelLayout);
        clientPanelLayout.setHorizontalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        clientPanelLayout.setVerticalGroup(
            clientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        mainPane.add(clientPanel, "card2");

        stockPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        mainPane.add(stockPanel, "card2");

        clientButton.setText("Client");
        clientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientButtonMouseClicked(evt);
            }
        });
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });

        tradingExButton.setText("Trading Exc.");
        tradingExButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tradingExButtonMouseClicked(evt);
            }
        });

        stockButton.setText("Stock");
        stockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockButtonMouseClicked(evt);
            }
        });
        stockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Upload New Dataset");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Settings");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tradingExButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientButton)
                        .addGap(10, 10, 10)
                        .addComponent(stockButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientButton)
                    .addComponent(tradingExButton)
                    .addComponent(stockButton))
                .addGap(13, 13, 13)
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientButtonMouseClicked
        clientPanel.setVisible(true);
        tradingExchangePanel.setVisible(false);
        stockPanel.setVisible(false);
    }//GEN-LAST:event_clientButtonMouseClicked

    private void tradingExButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tradingExButtonMouseClicked
        clientPanel.setVisible(false);
        tradingExchangePanel.setVisible(true);
        stockPanel.setVisible(false);
    }//GEN-LAST:event_tradingExButtonMouseClicked

    private void stockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockButtonMouseClicked
        clientPanel.setVisible(false);
        tradingExchangePanel.setVisible(false);
        stockPanel.setVisible(true);


    }//GEN-LAST:event_stockButtonMouseClicked

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientButtonActionPerformed

    private void stockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        settingsFrame.setVisible(true);
        settingsFrame.setAlwaysOnTop(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    private File chooseDSetButtonMouseClicked(java.awt.event.MouseEvent evt) {
        File tempFile = null;
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            tempFile = fileChooser.getSelectedFile();
        }
        return tempFile;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clientButton;
    private javax.swing.JPanel clientPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JFrame settingsFrame;
    private javax.swing.JButton stockButton;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JButton tradingExButton;
    private javax.swing.JPanel tradingExchangePanel;
    // End of variables declaration//GEN-END:variables

    private Object[] initialSetup() {

        JLabel companyFileName = new JLabel();

        JLabel clientFileName = new JLabel();
        companyFileName.setText("File Path");
        clientFileName.setText("File Path");
        JTextField traderCountInput = new JTextField(2);
        traderCountInput.setText("2");

        JOptionPane initOpPane;
        JButton chooseCompDSetButton = new JButton("Choose Company File");
        JButton chooseClientDSetButton = new JButton("Choose Client File");
        chooseCompDSetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                File tempFile = chooseDSetButtonMouseClicked(evt);
                if (tempFile != null) {
                    companyFileName.setText(tempFile.getPath());

                } else {

                }
                setCompFile(tempFile);

            }
        });

        chooseClientDSetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                File tempFile = chooseDSetButtonMouseClicked(evt);
                if (tempFile != null) {
                    clientFileName.setText(tempFile.getPath());

                } else {

                }
                setClientFile(tempFile);

            }
        });

        int traderCount = Integer.parseInt(traderCountInput.getText());

        Object[] options = {"Go", "Cancel"};

        Object[] obs = {companyFileName, chooseCompDSetButton, clientFileName, chooseClientDSetButton, traderCount};

        //initOpPane = new JOptionPane(obs,JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION, null, options, options[0]);
        return new Object[]{JOptionPane.showOptionDialog(null, obs, "Initial Setup", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]), traderCount};

    }

    private void setCompFile(File file) {
        compFile = file;
    }

    private void setClientFile(File file) {
        clientFile = file;
    }

    public File[] getFile() {

        return new File[]{compFile, clientFile};
    }
    public int getTraderCount(){
        return traderCount;
    }
}
